ge1/urls.py
from django.contrib import admin
from django.urls import path, include

""" ------------------------------------------------------------------------------ Imports ----- """
from django.shortcuts import render_to_response, HttpResponseRedirect, HttpResponse, render
from front1.views import *



""" ------------------------------------------------------------------------------ Imports ----- """

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inicio-Sesion/', inicioSesion),
    path('inicio/', inicio),

    # URL's TABLERO MANDO
    path('tablero-Mando/', include('tableroMando.urls'))
    
]

tableroMando/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views


""" ------------------------------------------------------------------------------ Imports ----- """
from django.shortcuts import render_to_response, HttpResponseRedirect, HttpResponse, render
from front1.views import *
from tableroMando.views import *

from django.conf.urls import url

""" ------------------------------------------------------------------------------ Imports ----- """

urlpatterns = [
    
    # INICIO TABLERO DE MANDO
    path('inicio-TableroMando/', inicioTableroMando, name='inicio'),
    # PROGRAMACION
    # path('programacion/', programacion),

    # SEGUIMIENTO
    path('seguimiento/', seguimiento),

    # VER INDICADORES CREADOS

    # NUEVO INDICADOR
    # url(r'^nuevo_indicador/$', views.nuevo_indicador),

    # path('nuevo_indicador/', views.nuevo_indicador, name='nuevo_indicador'),
    # path('listar_indicadores/', listar_indicadores),
    # path('eliminar_indicador/', views.eliminar_indicador, name='eliminar_indicador'),
    # path('agregar_medicion/', views.agregar_medicion, name='agregar_medicion'),
    
    path('indicador/', ConfiguracionIndicador.as_view(), name='indicador'),

    path('programacion/', ProgramacionIndicador.as_view(), name='programacion'),


]   

tableroMando/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, Group
from multiselectfield import MultiSelectField
from ge1.models import SisCargos, SisUnidadesMedida

# DIARIO = 1
# SEMANAL = 2
# QUINCENAL = 3
MENSUAL = 4
BIMENSUAL = 5 
TRIMESTRAL = 6
CUATRIMESTRAL = 7
SEMESTRAL = 8
ANUAL = 9
# BIENAL = 10
# TRIENAL = 11
# CUATRIENAL = 12
# OTRO = 13

PERIODICIDAD_OPCIONES = (
	# (DIARIO, 'Diario'),
	# (SEMANAL, 'Semanal'),
	# (QUINCENAL, 'Quincenal'),
	(MENSUAL, 'Mensual'),
	(BIMENSUAL, 'Bimensual'),
	(TRIMESTRAL, 'Trimestral'),
	(CUATRIMESTRAL, 'Cuatrimestral'),
	(SEMESTRAL, 'Semestral'),
	(ANUAL, 'Anual'),
	# (BIENAL, 'Bienal'),
	# (TRIENAL, 'Trienal'),
	# (CUATRIENAL, 'Cuatrienal'),
	# (OTRO, 'Otro'),
)

class NombreIndicador(models.Model):
	nombre = models.CharField(max_length=300,unique=True)

	def __str__(self):
		return u'%s' % (self.nombre)


class Indicador(models.Model):

# IDENTIFICADOR
	PLAN_DE_DESARROLLO = 1
	SISTEMA_DE_SALUD = 2
	SISTEMA_DE_GESTION = 3
	FINANCIERO = 4

	ABREBIATURA_INDICADORES = (
		(PLAN_DE_DESARROLLO, 'PDI'),
		(SISTEMA_DE_SALUD, 'SSS'),
		(SISTEMA_DE_GESTION, 'SGC'),
		(FINANCIERO, 'FIN'),
	)

	TIPO_INDICADOR_OPCIONES = (
		(PLAN_DE_DESARROLLO, 'Plan de desarrollo'),
		(SISTEMA_DE_SALUD, 'Sistema de salud'),
		(SISTEMA_DE_GESTION, 'Sistema de gestion'),
		(FINANCIERO, 'Financiero'),
	)
	
	# PIB = 'PIB'
	# NBI = 'NBI'
	# TDE = 'TDE'
	# PEA = 'PEA'

	# NOMENCLADOR_OPCIONES = (
	# 	(PIB, 'Producto Interno Bruto'),
	# 	(NBI, 'Necesidades Basicas Insatisfechas'),
	# 	(TDE, 'Tasa de Desercion Escolar'),
	# 	(PEA, 'Poblacion Economicamente Activa'),
	# )

	MANUAL = 1
	AUTOMATICO = 2
	TIPOS_MEDICIONES = (
		(MANUAL, 'Manual'),
		(AUTOMATICO, 'Automatico'),
	)

	ANUAL = 1
	BIENAL = 2
	TRIENAL = 3
	CUATRIENAL = 4
	QUINQUENAL = 5
	DECENAL = 10

	CICLO_OPCIONES = (
		(ANUAL, 'Anual'),
		(BIENAL, 'Bienal'),
		(TRIENAL, 'Trienal'),
		(CUATRIENAL,'Cuatrienal'),
		(QUINQUENAL, 'Quinquenal'),
		(DECENAL, 'Decenal'),

	)

	IMPACTO = 1
	GESTION = 2
	RESULTADO = 3
	PROCESO = 4
	PRODUCTO = 5
	EFECTO = 6
	ACCION = 7
	RECURSO = 8

	AMBITOS = (
		(IMPACTO, 'Impacto'),
		(GESTION, 'Gestion'),
		(RESULTADO, 'Resultado'),
		(PROCESO, 'Proceso'),
		(PRODUCTO, 'Producto'),
		(EFECTO, 'Efecto'),
		(ACCION, 'Accion'),
		(RECURSO, 'Recurso'),
	)

	EFICACIA = 1
	EFICIENCIA = 2
	EFECTIVIDAD = 3
	ECONOMIA = 4
	SEGURIDAD = 5
	CALIDAD = 6
	ATENCION = 7
	EQUIDAD = 8

	DIMENCIONES = (
		(EFICACIA, 'Eficacia'),
		(EFICIENCIA, 'Eficiencia'),
		(EFECTIVIDAD, 'Efectividad'),
		(ECONOMIA, 'Economia'),
		(SEGURIDAD, 'Seguridad'),
		(CALIDAD, 'Calidad'),
		(ATENCION, 'Atencion'),
		(EQUIDAD, 'Equidad'),
	)

	RESOLUCION_256 = 1
	RESOLUCION_742 = 2
	DECRETO_2193 = 3
	RESOLUCION_1552 = 4
	CIRCULAR_030 = 5
	NORMATIVIDAD_INTERNA = 6
	NORMATIVIDAD_OPCIONES = (
		(RESOLUCION_256, 'Resolucion 256'),
		(RESOLUCION_742, 'Resolucion 743'),
		(DECRETO_2193, 'Decreto 2193'),
		(RESOLUCION_1552, 'Resolución 1552'),
		(CIRCULAR_030, 'Circular 030'),
		(NORMATIVIDAD_INTERNA, 'Normatividad Interna'),
	)

	PRIMERO = 1
	SEGUNDO = 2
	TERCERO = 3
	CUARTO = 4
	QUINTO = 5
	SEXTO = 6
	SEPTIMO = 7 
	OCTAVO = 8
	NOVENO = 9
	DECIMO = 10
	QUINCE = 15
	VEINTE = 20
	VEINTI_CINCO = 25
	ULTIMO_DIA_MES = 28

	LIMITES_REPORTES = (
		(PRIMERO, 'Primero día hábil del siguiente periodo'),
		(SEGUNDO, 'Segundo día hábil del siguiente periodo'),
		(TERCERO, 'Tercero día hábil del siguiente periodo'),
		(CUARTO, 'Cuarto día hábil del siguiente periodo'),
		(QUINTO, 'Quinto día hábil del siguiente periodo'),
		(SEXTO, 'Sexto día hábil del siguiente periodo'),
		(SEPTIMO, 'Septimo día hábil del siguiente periodo'),
		(OCTAVO, 'Octavo día hábil del siguiente periodo'),
		(NOVENO, 'Noveno día hábil del siguiente periodo'),
		(DECIMO, 'Decimo día hábil del siguiente periodo'),
		(QUINCE, 'Día quince del siguiente periodo'),
		(VEINTE, 'Día veinte del siguiente periodo'),
		(VEINTI_CINCO, 'Día veinti cinco del siguiente periodo'),
		(ULTIMO_DIA_MES, 'Día ultimo dia mes del siguiente periodo'),
	)

	estado				= models.BooleanField(default=True)  #  estado para inactivar en caso de eliminar	
	tipo_indicador 		= MultiSelectField(max_length=10,choices=TIPO_INDICADOR_OPCIONES, default="")
	consecutivo			= models.IntegerField()
	nombre_indicador 	= models.ForeignKey(NombreIndicador, on_delete=models.DO_NOTHING,blank=True, null=True)
	objetivo  			= models.TextField(blank=True, null=True)
	producto_mide		= models.TextField(blank=True, null=True)
	tipo_medicion		= models.SmallIntegerField(choices=TIPOS_MEDICIONES, default=MANUAL)
	ciclo				= models.SmallIntegerField(choices=CICLO_OPCIONES, default=CUATRIENAL)
	periodicidad		= models.SmallIntegerField(choices=PERIODICIDAD_OPCIONES, default=SEMESTRAL)
	ambito				= models.SmallIntegerField(choices=AMBITOS, default=RESULTADO)
	dimension			= models.SmallIntegerField(choices=DIMENCIONES, default=EFICACIA)
	responsable			= models.ForeignKey(SisCargos, on_delete=models.DO_NOTHING)
	normatividad 		= MultiSelectField(max_length=10,choices=NORMATIVIDAD_OPCIONES)
	fecha_registro		= models.DateTimeField(editable=False) #DateTimeField(default=timezone.now) -- DateField()
	fecha_modificacion	= models.DateTimeField() # Esta fecha se eactualiza cada vez que se actualiza
	fecha_actualizacion	= models.DateTimeField()
	limite_reporte   	= models.SmallIntegerField(choices=LIMITES_REPORTES, default=SEGUNDO)
	version    			= models.FloatField(default="1")
	recurrencia			= models.NullBooleanField(default=True)
	verificado 			= models.BooleanField(default=False)
	# nombre_identificador= models.CharField(max_length = 300,blank=True, null=True)
	# tipo	  			= models.SmallIntegerField(choices=TIPO_INDICADOR_OPCIONES, default=PLAN_DE_DESARROLLO)
	# nomenclador			= models.CharField(choices=NOMENCLADOR_OPCIONES, max_length = 3, default=TDE)
	# usuario_registro 	= models.ForeignKey(User, on_delete=models.DO_NOTHING)

	# ARMONIZACION
	
	# def get_prefijo(self):
	# 	return self.ABREBIATURA_INDICADORES[self.tipo-1][1]


	def str_codigo(self):
		return u'IND - %s' % (self.consecutivo)


	def save(self, *args, **kwargs):
		if not self.id:
			self.fecha_registro = timezone.now()
			self.fecha_actualizacion = timezone.now()
		self.fecha_modificacion = timezone.now()
		return super(Indicador, self).save(*args, **kwargs)	


	# def get_medicion(self):
	# 	return Medicion.objects.get()


	def __str__(self):
		return u'IND - %s %s' % (self.consecutivo, self.nombre_indicador)



class Medicion(models.Model):
	#MEDICION
	PORCENTAJE = 1
	TASA_VARIACION = 2
	PROMEDIO = 3
	NUMERO_ENTERO = 4

	TIPOS_FORMULA = (
		(PORCENTAJE, 'Porcentaje'),
		(TASA_VARIACION, 'Tasa de variación'),
		(PROMEDIO, 'Promedio'),
		(NUMERO_ENTERO, 'Numero entero'),
	)

	INCREMENTO = 1
	MANTENIMIENTO = 2
	DISMINUCION = 3

	TENCENCIAS_MEDICION = (
		(INCREMENTO, 'Incremento'),
		(MANTENIMIENTO, 'Mantenimiento'),
		(DISMINUCION, 'Disminucion'),
	)

	FORMULAS_PREDETERMINADAS = (
		(TASA_VARIACION, '$$TDE = {NEAG(Tn) - NEAG(T0) \over NEAG(T0) }X 100$$'),
		(PORCENTAJE, '$$TDE = {NEAG \over NEM }X 100$$'),
		(PROMEDIO, '$$TDE = {NEC \over NGC }$$'),
		(NUMERO_ENTERO, '$$TDE = {NEC}$$'),
	)

	indicador 			= models.OneToOneField(Indicador, on_delete=models.CASCADE, primary_key=True)
	tipo_formula 		= models.SmallIntegerField(choices=TIPOS_FORMULA, default=TASA_VARIACION)
	unidad_medicion		= models.ForeignKey(SisUnidadesMedida, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='+')
	tendencia 			= models.SmallIntegerField(choices=TENCENCIAS_MEDICION, default=INCREMENTO)
	archivo_asociado 	= models.CharField(max_length = 100, blank=True, null=True)

	nombre_variable_1	= models.CharField(max_length = 200)
	nomenclaruta_1 		= models.CharField(max_length = 6)
	unidad_1			= models.ForeignKey(SisUnidadesMedida, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='+')
	fuente_1			= models.CharField(max_length = 100, blank=True, null=True)

	nombre_variable_2	= models.CharField(max_length = 200, blank=True, null=True)
	nomenclaruta_2 		= models.CharField(max_length = 6, blank=True, null=True)
	unidad_2			= models.ForeignKey(SisUnidadesMedida, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='+')
	fuente_2			= models.CharField(max_length = 100, blank=True, null=True)

	nombre_respuesta	= models.CharField(max_length = 200, blank=True, null=True)
	nomenclaruta_respuesta = models.CharField(max_length = 6, blank=True, null=True)
	unidad_respuesta	= models.ForeignKey(SisUnidadesMedida, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='+')
	fuente_respuesta	= models.CharField(max_length = 100, blank=True, null=True)

	formula 			= models.TextField()
	
	interpretacion_resultado = models.TextField(blank=True, null=True)
	rango_inicial 		= models.IntegerField(blank=True, null=True)
	rango_final 		= models.IntegerField(blank=True, null=True)
	responsable_reporte = models.ForeignKey(SisCargos, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='+')
	responsable_consolidacion = models.ForeignKey(SisCargos, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='+')
	responsable_analisis_seguimiento = models.ForeignKey(SisCargos, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='+')
	responsable_decisiones = models.ForeignKey(SisCargos, on_delete=models.DO_NOTHING, blank=True, null=True, related_name='+')

	def __str__(self):
		return u'%s -- %s' % (self.indicador, self.tipo_formula)


# [BD-PRO] agrego a tabla subprocesos, CONSTRAINT subprocesos_codigo_key UNIQUE (codigo) 
# Se deja solo codigo como primary_key (Para que no halla error en django)
# si llega a haber una llave igual de codigo en la tabla subprocesos habrá error, no se puede controlar desde esta aplicacion
from ge1.models import PdeMetas, Procesos, Subprocesos, PdeUnidadNivel, SisMultivalores
class Armonizacion(models.Model):
	ESTRATEGICO = 1
	MISIONAL = 2
	APOYO = 3
	EVALUACION = 4

	TIPOS_PROCESOS = (

tableroMando/forms.py
from django import forms
from .models import Indicador, Medicion, Armonizacion


class IndicadorFormulario(forms.ModelForm):
	class Meta:
		model = Indicador
		exclude = (
			'fecha_creacion',
			'fecha_modificacion',
			'rango_inicial',
			'rango_final',
			# 'tipo',
			# 'usuario_registro',
			)
		fields = (
			'tipo_indicador',
			'consecutivo',
			'nombre_indicador',
			'objetivo',
			'producto_mide',
			'tipo_medicion',
			'ciclo',
			'periodicidad',
			'ambito',
			'dimension',
			'responsable',
			'fecha_actualizacion', # fecha que actualiza el indicador
			'normatividad',
			'limite_reporte',
			'version',
			'recurrencia',
			)
		widgets = {
            'normatividad': forms.SelectMultiple(attrs={'class': 'form-control','multiple':'','data-placeholder':'Seleccione algunas opciones'}),
            'tipo_indicador': forms.SelectMultiple(attrs={'class': 'form-control','multiple':'','data-placeholder':'Seleccione algunas opciones'}),
        }

	# Constructor que asigna form-control a todos los elemtos del formulario
	def __init__(self, *args, **kwargs):
		super(IndicadorFormulario, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'

		self.fields['objetivo'].widget.attrs['rows']= 2
		self.fields['producto_mide'].widget.attrs['rows']= 2
		self.fields['fecha_actualizacion'].required = False
		
		# Desactivar fields
		self.fields['version'].required = False
		self.fields['tipo_medicion'].required = False
		self.fields['recurrencia'].required = False
		self.fields['version'].widget.attrs['disabled'] = 'disabled'
		self.fields['tipo_medicion'].widget.attrs['disabled'] = 'disabled'
		self.fields['recurrencia'].widget.attrs['disabled'] = 'disabled'



class MedicionForm(forms.ModelForm):
	class Meta:
		model = Medicion
		exclude = ('indicador',)
		fields = (
			'tipo_formula',
			'unidad_medicion',
			'tendencia',
			'archivo_asociado',
			'nombre_variable_1',
			'nomenclaruta_1',
			'unidad_1',
			'fuente_1',
			
			'nombre_variable_2',
			'nomenclaruta_2',
			'unidad_2',
			'fuente_2',

			'nombre_respuesta',
			'nomenclaruta_respuesta',
			'unidad_respuesta',
			'fuente_respuesta',

			'formula',
			'interpretacion_resultado',
			'rango_inicial',
			'rango_final',
			'responsable_reporte',
			'responsable_consolidacion',
			'responsable_analisis_seguimiento',
			'responsable_decisiones',
		)

	def __init__(self, *args, **kwargs):
		super(MedicionForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control'
		self.fields['interpretacion_resultado'].widget.attrs['rows']= 3
		self.fields['formula'].widget.attrs['rows']= 2


class ArmonizacionForm(forms.ModelForm):
	class Meta:
		model = Armonizacion
		exclude = ('indicador',)
		fields = (
			'linea',
			'meta',
			'tipo_proceso',
			'proceso',
			'programa',
			'subprograma',
			'subproceso',
			'tipo_armonizacion',
			)
		widgets = {
            'tipo_armonizacion': forms.SelectMultiple(attrs={'multiple':''}),
        }

	def  __init__(self, *args, **kwargs):
		super(ArmonizacionForm, self).__init__(*args, **kwargs)
		for visible in self.visible_fields():
			visible.field.widget.attrs['class'] = 'form-control select-chossen'


class FiltrosIndicadoresForm(forms.Form):

	def __init__(self, *args, **kwargs):
		super(FiltrosIndicadoresForm, self).__init__(*args, **kwargs)
		# formulario
		self.fields['codigo_indicador'] = forms.IntegerField(required=False)
		choices_n = [(0, 'Ninguno'),]
		choices_n.extend([(i.id, i.nombre_indicador.nombre) for i in Indicador.objects.filter(estado=True)])
		self.fields['nombre_indicador'] = forms.ChoiceField(choices=choices_n, required=False)

		choices_t = [(0, 'Ninguno'),]
		choices_t.extend(Indicador.TIPO_INDICADOR_OPCIONES)
		self.fields['tipo_proceso'] = forms.ChoiceField(choices=choices_t, required=False)

		choices_c = [(0, 'Ninguno'),]
		choices_c.extend(Indicador.CICLO_OPCIONES)
		self.fields['ciclo'] = forms.ChoiceField(choices=choices_c, required=False)
		
		#atributos
		self.fields['codigo_indicador'].widget.attrs['class'] = 'col-sm-7 form-control form-control-sm'
		self.fields['codigo_indicador'].widget.attrs['placeholder'] ='Digita el código'
		self.fields['nombre_indicador'].widget.attrs['class'] = 'col-sm-7 form-control form-control-sm'
		self.fields['tipo_proceso'].widget.attrs['class'] = 'col-sm-7 form-control form-control-sm'
		self.fields['ciclo'].widget.attrs['class'] = 'col-sm-8 form-control form-control-sm'

tableroMando/templates/programacion/informacion_base.html
<div class="col-md-12">
	<div class="row">
		<div class="col-md-6">
			<b>CODIGO: </b>{{indicador.str_codigo}}
		</div>
		<div class="col-md-6">
			<b>TIPO INDICADOR: </b>{{indicador.tipo_indicador}}
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<b>NOMBRE: </b>{{indicador.nombre_identificador}}
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<b>OBJETIVO: </b>{{indicador.objetivo}}
		</div>
		<div class="col-md-6">
			<b>PRODUCTO QUE MIDE: </b>{{indicador.producto_mide}}
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-md-3">
			<b>Ciclo: </b>{{indicador.get_ciclo_display}}
		</div>
		<div class="col-md-3">
			<b>Periodicidad: </b>{{indicador.get_periodicidad_display}}
		</div>
		<div class="col-md-3">
			<b>Ambito: </b>{{indicador.get_ambito_display}}
		</div>
		<div class="col-md-3">
			<b>Dimension: </b>{{indicador.get_dimension_display}}
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<b>Responsable: </b>{{indicador.responsable}}
		</div>
		<div class="col-md-6">
			<b>Normatividad: </b>{{indicador.normatividad}}
		</div>
	</div>
	<div class="row">
		<div class="col-md-6">
			<b>Limite reporte: </b>{{indicador.get_limite_reporte_display}}
		</div>
		<div class="col-md-3">
			<b>Version: </b>{{indicador.version}}
		</div>
		<div class="col-md-3">
			<b>Version: </b>{{indicador.fecha_registro|date:"d/m/Y"}}
		</div>
	</div>
	<br>
	
	<div class="row">
		<div class="col-md-4">
			<b>PLAN DE DESARROLLO</b>
			<br>
			<b>Linea: </b> {{indicador.armonizacion.linea}}<br>
			<b>Programa: </b> {{indicador.armonizacion.programa}}<br>
			<b>Subprograma: </b> {{indicador.armonizacion.subprograma}}<br>
			<b>Meta: </b> {{indicador.armonizacion.meta}}<br>
		</div>
		<div class="col-md-4">
			<b>SISTEMA INTEGRADO DE GESTIÓN</b>
			<br>
			<b>Tipo de proceso: </b> {{indicador.armonizacion.get_tipo_proceso_display}}<br>
			<b>Proceso: </b> {{indicador.armonizacion.proceso}}<br>
			<b>Subproceso: </b> <br>
		</div>
		<div class="col-md-4">
			<b>MODELO INTEGRADO DE PLANEACIÓN Y GESTIÓN</b>

			<b></b>
			<b></b>
			<b></b>
		</div>
	</div>
	
	<br>

	<div class="row">
		<div class="col-md-3">
			<label><b>Responsable Reporte</b></label><br>
			{{indicador.medicion.responsable_reporte}}
		</div>
		<div class="col-md-3">
			<label><b>Responsable Consolidacion</b></label><br>
			{{indicador.medicion.responsable_consolidacion}}
		</div>
		<div class="col-md-3">
			<label><b>Responsable Analisis Seguimiento</b></label><br>
			{{indicador.medicion.responsable_analisis_seguimiento}}
		</div>
		<div class="col-md-3">
			<label><b>Responsable Decisiones</b></label><br>
			{{indicador.medicion.responsable_decisiones}}
		</div>
	</div>
</div>

tableroMando/templates/programacion/ver_programacion.html
{% extends "plantilla.html" %}
{% load static %}
{% block title %}Programación - Informacion base{% endblock title %}

{% block extra_header %}
	<script src="{% static 'librerias/library/bootstrap-slider-master/bootstrap-slider.min.js' %}"></script>
	<link href="{% static 'librerias/library/bootstrap-slider-master/css/bootstrap-slider.min.css' %}" rel="stylesheet" type="text/css" media="screen">
	<script src="{% static 'librerias/chosen_v1.8.5/chosen.jquery.min.js' %}"></script>
	<link href="{% static 'librerias/chosen_v1.8.5/chosen.min.css' %}" rel="stylesheet" type="text/css">
	<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=AM_CHTML"></script>

{% endblock extra_header %}

{% block contenido %}

<div class="container-fluid">
	<nav aria-label="breadcrumb">
	  <ol class="breadcrumb">
		<li class="breadcrumb-item"><a href="{% url 'indicador' %}?listar_i">Indicadores</a></li>
		<li class="breadcrumb-item"><a href="{% url 'indicador' %}?ver&indicador={{indicador.id}}">Indicador: {{indicador.str_codigo }}</a></li>
		<li class="breadcrumb-item active" aria-current="page">Programación</li>
	  </ol>
	</nav>
</div>

<div class="container">
<table class="table table-bordered table-striped" style="margin-top: 10px">
	<thead class="bg-primary">
		<tr>
			<th class="text-white">PROGRAMACIÓN</th>
		</tr>
	</thead>
	<tbody>
	<tr>
	<td>
		<div class="card text-center">

			<div class="card-header bg-light" id="nav_tabs">
				<ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
					<li class="nav-item">
						<a class="nav-link active" id="info_base-tab" data-toggle="tab" href="#info_base" role="tab" aria-controls="info_base" aria-selected="true">INFORMACION BASE</a>
				  	</li>
					<li class="nav-item">
					    <a class="nav-link" id="programacion_inicial-tab" data-toggle="tab" href="#programacion_inicial" role="tab" aria-controls="programacion_inicial" aria-selected="false">PROGRAMACIÓN INICIAL</a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" id="plan_inactivo-tab" data-toggle="tab" href="#plan_inactivo" role="tab" aria-controls="plan_inactivo" aria-selected="false">PLAN INDICATIVO</a>
					</li>
				</ul>
			</div>


			<div class="card-body">
				<div class="tab-content text-left">
					<div class="tab-pane fade show active" id="info_base" role="tabpanel" aria-labelledby="info_base-tab">
						{% include 'programacion/informacion_base.html' %}
					</div>

					<div class="tab-pane fade" id="programacion_inicial" role="tabpanel" aria-labelledby="programacion_inicial-tab">
						{% include 'programacion/programacion_inicial.html' %}
					</div>

					<div class="tab-pane fade" id="plan_inactivo" role="tabpanel" aria-labelledby="plan_inactivo-tab">
						{% include "programacion/plan_indicativo.html" %}
					</div>
				</div>
			</div><!-- DIV PANE -->

		</div>
	</td>
	</tr>
</tbody>
</table>
</div>

{% endblock contenido %}


{% block extra_script %}

<script type="text/javascript">

</script>

{% endblock extra_script %}